version: "3"
services:
  postgres:
    image: postgres:11
    container_name: postgres-task-manager
    ports:
      - 5432:5432
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: postgres

