version: "3"
services:
  postgres:
    image: postgres:11
    container_name: postgres-task-manager
    ports:
      - 5432:5432
    volumes:
      - postgres-task-manager:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin

volumes:
  postgres-task-manager:
  localstack-task-manager:
